version: '3'
services:

  worker_container:
    container_name: worker_container
    command: /start.sh
    env_file:
      - .env
    working_dir: /opt/worker
    volumes:
      - ../src:/opt/worker
    depends_on:
      - postgres
    links:
      - postgres

  worker_interface:
    container_name: worker_interface
    working_dir: /opt/worker_interface
    command: /start_interface.sh
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:9.3
    env_file:
      - .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /tmp
